version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: node:12

commands:
  load_package:
    steps:
      - restore_cache:
          name: Restore pnpm Package Cache
          keys: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}

  save_package:
    steps:
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths: .pnpm-store

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-8 --activate
            pnpm config set store-dir .pnpm-store
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_package

  lint:
    executor:
      name: default
    steps:
      - checkout
      - load_package
      - run:
          name: Lint Prettier
          command: pnpm run lint:format
      - save_package

workflows:
  pull-request:
    jobs:
      - setup
      - lint:
        requires:
          - setup
