version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: node:20

commands:
  install_pnpm:
    steps:
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-8 --activate
            pnpm config set store-dir .pnpm-store
  install_package:
    steps:
      - run:
          name: Install Dependencies
          command: |
            pnpm install
  load_package:
    steps:
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
  save_package:
    steps:
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - .pnpm-store
  lint_format:
    steps:
      - run:
          name: Lint Prettier
          command: pnpm run lint:format

jobs:
  setup:
    executor:
      name: default
    resource_class: large
    parallelism: 10
    steps:
      - checkout
      - load_package
      - install_pnpm
      - install_package
      - lint_format
      - save_package

workflows:
  pull-request:
    jobs:
      - setup
