version: 2.1

executors:
  node_executor:
    docker:
      - image: cimg/node:20.11.0
    working_directory: ~/project

commands:
  install_package:
    steps:
      - run:
          name: Install Dependencies
          command: pnpm install
  install_browser_v1:
    steps:
      - run:
          name: Install Playwright v1
          command: npx playwright install --with-deps
  install_browser_v2:
    steps:
      - run:
          name: Install Playwright v2
          command: npx playwright install chrome
  load_workspace:
    steps:
      - attach_workspace:
          at: .
  save_workspace:
    steps:
      - persist_to_workspace:
          root: ~/project
          paths: .
  lint_format:
    steps:
      - run:
          name: Lint Prettier
          command: pnpm run lint:format
  lint_style:
    steps:
      - run:
          name: Lint Stylelint
          command: pnpm run lint:style
  lint_script:
    steps:
      - run:
          name: Lint Eslint
          command: pnpm run lint:script
  test_ui:
    steps:
      - run:
          name: Test Storybook
          command: pnpm run test:ui.ci
  test_ut:
    steps:
      - run:
          name: Test Vitest
          command: pnpm run test:ut
  test_it:
    steps:
      - run:
          name: Test Playwright
          command: pnpm run test:it

jobs:
  setup:
    executor: node_executor
    steps:
      - checkout
      - install_package
      - save_workspace
  lint:
    executor: node_executor
    steps:
      - load_workspace
      - lint_format
      - lint_style
      - lint_script
  test_ui:
    executor: node_executor
    steps:
      - load_workspace
      - install_browser_v1
      - test_ui
  test_ut:
    executor: node_executor
    steps:
      - load_workspace
      - test_ut
  test_it:
    executor: node_executor
    steps:
      - load_workspace
      - install_browser_v2
      - test_it

workflows:
  ci:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test_ui:
          requires:
            - setup
      - test_ut:
          requires:
            - setup
      - test_it:
          requires:
            - setup
