version: 2.1

executors:
  node_executor:
    docker:
      - image: cimg/node:20.12.2
    working_directory: ~/project

commands:
  load_workspace:
    steps:
      - attach_workspace:
          at: .
  save_workspace:
    steps:
      - persist_to_workspace:
          root: ~/project
          paths: .
  install_pnpm:
    steps:
      - run: npm i -g pnpm@9.0.6
  install_package:
    steps:
      - run: pnpm install
  lint_format:
    steps:
      - run: pnpm lint:format
  lint_style:
    steps:
      - run: pnpm lint:style
  lint_script:
    steps:
      - run: pnpm lint:script
  test_ui:
    steps:
      - run: |
          npx playwright install --with-deps
          pnpm test:ui.ci
  test_ut:
    steps:
      - run: pnpm test:ut
  test_it:
    steps:
      - run: |
          npx playwright install chrome
          pnpm test:it

jobs:
  setup:
    executor: node_executor
    steps:
      - checkout
      - install_pnpm
      - install_package
      - save_workspace
  lint:
    executor: node_executor
    steps:
      - load_workspace
      - lint_format
      - lint_style
      - lint_script
  test_ut:
    executor: node_executor
    steps:
      - load_workspace
      - test_ut
  test_ui:
    executor: node_executor
    steps:
      - load_workspace
      - test_ui
  test_it:
    executor: node_executor
    steps:
      - load_workspace
      - test_it

workflows:
  ci:
    jobs:
      - setup
      # - lint:
      #     requires:
      #       - setup
      # - test_ut:
      #     requires:
      #       - setup
      # - test_ui:
      #     requires:
      #       - setup
      # - test_it:
      #     requires:
      #       - setup
