version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:20.11.0-browsers
    working_directory: ~/project

commands:
  install_pnpm:
    steps:
      - run:
          name: Install pnpm package manager
          command: |
            sudo corepack enable
            corepack prepare pnpm@latest-8 --activate
            pnpm config set store-dir .pnpm-store
  install_package:
    steps:
      - run:
          name: Install Dependencies
          command: pnpm install
  install_browser_v1:
    steps:
      - run:
          name: Install Playwright v1
          command: npx playwright install --with-deps
  install_browser_v2:
    steps:
      - run:
          name: Install Playwright v2
          command: npx playwright install chrome
  load_workspace:
    steps:
      - persist_to_workspace:
          root: ~/project
          paths: node_modules
  save_workspace:
    steps:
      - attach_workspace:
          at: .
  load_cache:
    steps:
      - restore_cache:
          name: Restore pnpm Package Cache
          keys: v1-packages-{{ checksum "pnpm-lock.yaml" }}
  save_cache:
    steps:
      - save_cache:
          name: Save pnpm Package Cache
          key: v1-packages-{{ checksum "pnpm-lock.yaml" }}
          paths: node_modules
  lint_format:
    steps:
      - run:
          name: Lint Prettier
          command: pnpm run lint:format
  lint_style:
    steps:
      - run:
          name: Lint Stylelint
          command: pnpm run lint:style
  lint_script:
    steps:
      - run:
          name: Lint Eslint
          command: pnpm run lint:script
  test_ui:
    steps:
      - run:
          name: Test Storybook
          command: pnpm run test:ui.ci
  test_ut:
    steps:
      - run:
          name: Test Vitest
          command: pnpm run test:ut
  test_it:
    steps:
      - run:
          name: Test Playwright
          command: pnpm run test:it

jobs:
  setup:
    executor: default
    steps:
      - checkout
      - install_pnpm
      - install_package
      - save_workspace
  test:
    executor: default
    steps:
      - checkout
      - install_pnpm
      - load_workspace
      - lint_format
      - lint_style
      - lint_script
      - install_browser_v1
      - test_ui
      - test_ut
      - install_browser_v2
      - test_it

workflows:
  pull-request:
    jobs:
      - setup
      - test
        requires:
          -setup
