name: ContinuousIntegration
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.5.1
      - run: npm install
      - run: npm run lint:format
      - run: npm run lint:style
      - run: npm run lint:script
      - run: npm run test:unit
      - run: npm run test:e2e
